### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by StefanGreve** [Advanced-Systems/backend#6]
## Task

Containerize this backend with a docker image for deployment on Linux.

- [x] create docker image and expose port 5000 over HTTP
- [ ] add a `docker-compose.yml` file for configuring `redis` and `postgresql`
- [ ] also expose port 5001 over HTTPS and use a certificate

## Further Reading:

- https://learn.microsoft.com/en-us/dotnet/architecture/containerized-lifecycle/design-develop-containerized-apps/build-aspnet-core-applications-linux-containers-aks-kubernetes
- https://github.com/tumugin/lullaby/tree/main

## Note:

Starting with .NET 7, it's also possible to creative a container without using explicitly docker:

- https://www.youtube.com/watch?v=3s-RfwvijpY

However, in this project we will keep using plain old docker files for the time being.
